$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf


$GTK_THEME = Vanta-Black
$ICON_THEME = Tela-circle-black
$COLOR_SCHEME=prefer-dark
$CURSOR_THEME = Bibata-Modern-Ice
$CURSOR_SIZE=20
$CODE_THEME=Pure Black

exec = gsettings set org.gnome.desktop.interface icon-theme '$ICON_THEME'
exec = gsettings set org.gnome.desktop.interface gtk-theme '$GTK_THEME'
exec = gsettings set org.gnome.desktop.interface color-scheme '$COLOR_SCHEME'
exec = Hyde cursor theme '$CURSOR_THEME' size $CURSOR_SIZE
exec = Hyde code theme '$CODE_THEME'

general {
    gaps_in = 5
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(303030ee) rgba(1a1a1ab0) rgba(1a1a1ab0) rgba(303030ee) 45deg
    col.inactive_border = rgba(1a1a1ab0) rgba(000000b0) rgba(000000b0) rgba(1a1a1ab0) 45deg
    resize_on_border = yes
}

decoration {
    rounding = 5

    active_opacity = 0.95
    inactive_opacity = 0.8

    blur {
        enabled = yes
        size = 10
        passes = 4
        ignore_opacity = true
        new_optimizations = true
        xray = false
        noise = 0.0
        popups = true
    }

    dim_inactive = false
    dim_strength = 0.05

    shadow {
        enabled = false
        range = 30
        scale = 2
        render_power = 5
        color = rgba(0f0f0fff)
        color_inactive = rgba(050505ff)
    }
}

group {
    col.border_inactive = rgba(1a1a1ab0)
    col.border_active = rgba(ffffffee) rgba(bfbfbfb0) rgba(bfbfbfb0) rgba(ffffffee) 45deg

    groupbar {
        col.active = rgba(bfbfbfcc)
        col.inactive = rgba(82828299)
        font_family = JetBrainsMono NFM
        font_size = 10
        text_color = rgba(ffffffff)
    }
}


layerrule = unset,waybar
